#!/usr/bin/env bash

# PROJECT_DIR: Default to the 3rd parent directory
: "${PROJECT_DIR:=$(realpath ../../..)}"
# PROJECT_BRANCH: Default to the active branch of PROJECT_DIR
: "${PROJECT_BRANCH:=$(git -C "$PROJECT_DIR" rev-parse --abbrev-ref HEAD)}"

# Debugging: Print the environment variables
# echo "PROJECT_DIR: $PROJECT_DIR"
# echo "PROJECT_BRANCH: $PROJECT_BRANCH"

set -e

help-table() {
    local cmd_width=55
    local desc_width=50
    local column="| %-${cmd_width}s | %-${desc_width}s |\n"

    printf "$column" "Command" "Description"
    echo "|$(printf '%*s' $((cmd_width + 2)) '' | tr ' ' '-')|$(printf '%*s' $((desc_width + 2)) '' | tr ' ' '-')|"

    printf "$column" "help [grep]" "Show help for commands."
    printf "$column" "git_name_email <name> <email>" "Configure Henrik's global Git settings."
    printf "$column" "dev_fix_module <version> <module> <repo_src> <repo_fix>" "Create a branch to fix a module."
}

help() {
    echo
    if [[ -n "$1" ]]; then
        help-table | grep -i "$1" | column -t -s'|'
    else
        echo "task <command> [options]"
        echo
        echo "commands:"
        echo
        help-table
    fi
    echo
}

###########################################################

# DO FIRST TIME

git_name_email() {
    git config --global user.name "$1"
    git config --global user.email "$2"
    mkdir -p ~/.ssh
}

run_python_or_fail() {
    local error_message="$1"
    shift

    if ! python "$@"; then
        echo "$error_message" >&2
        exit 1
    fi
}

dev_fix_module() {
    VERSION=$1 # e.g. 19.0
    MODULE=$2 # e.g. res_company_search_view
    REPO_SRC=$3 # e.g. OCA/multi-company
    REPO_FIX=$4 # e.g. norlinhenrik/oca-multi-company

    BRANCH_SRC="${VERSION}"
    BRANCH_FIX="${VERSION}-fix-${MODULE}"

    run_python_or_fail "could not clone $REPO_SRC" local-dev/gitclone.py git@github.com:$REPO_SRC.git -b $BRANCH_SRC
    run_python_or_fail "could not clone $REPO_FIX" local-dev/gitclone.py git@github.com:$REPO_FIX.git

    cd ~/src/gh/$REPO_FIX
    git worktree add $BRANCH_FIX
    cd $BRANCH_FIX
    git rm -rf .
    cp -r ~/src/gh/$REPO_SRC/$BRANCH_SRC/$MODULE .
    git add --all
    git commit -m "Initial commit for $BRANCH_FIX"
}

###########################################################

if declare -f "$1" > /dev/null; then
    "$1" "${@:2}"
else
    case "$1" in
        all)
            install
            lint
            ;;
        *)
            echo "Unknown command: $1"
            help
            exit 1
            ;;
    esac
fi
